FROM n8nio/n8n:latest

# Trocar para root temporariamente para instalar
USER root

# Instalar dependências e awscli em venv
RUN apk add --no-cache \
      curl \
      unzip \
      python3 \
      py3-pip && \
    python3 -m venv /home/node/awscli-venv && \
    /home/node/awscli-venv/bin/pip install --no-cache-dir awscli && \
    chown -R node:node /home/node/awscli-venv

# Volta para o usuário padrão "node"
USER node

# Atalho opcional: tornar aws acessível sempre ao entrar no container
ENV PATH="/home/node/awscli-venv/bin:$PATH"